config/routes.rb
Rails.application.routes.draw do
  resources :categories

  get 'pages/equipo'

  get 'pages/contacto'

  get 'pages/services'

  devise_for :users
  get 'comments/create'

  get 'comments/update'

  get 'comments/destroy'

  get 'myblogs' => 'blogs#myblogs'
 
  get 'blogs/:id/contactme' => 'blogs#contactme', as: :contactme
 
   

    
        
 
 
  resources :blogs, :path => ''

    resources :blogs do
       resources :posts do
          resources :comments
      end  
  end

 

  root 'blogs#index'

end

app/models/blog.rb
class Blog < ActiveRecord::Base

	#callbacks
	after_create :update_slug
	before_update :assign_slug
 

	#validacones
	validates :siteTitle, presence: { message: "ups requerido!"}
	validates :siteDescription, presence: { message: "ups requerido!"}
    validates :siteHeader, presence: { message: "ups requerido!"}
     
    #asociaciones
	belongs_to :user
	has_many :posts
	belongs_to :category
	
	#scope para ordenar registros de manera descendente por ID
	scope :sorted, -> {order('id desc')}
   	
   	def to_param
    	slug
  	end


	 private

		def assign_slug
		self.slug = "#{ siteTitle.parameterize }"
	 	end

		def update_slug
		update_attributes slug: assign_slug
		end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  #before_action :authenticate_user!, only: [:destroy, :new, :create, :edit, :update, :myblogs] #metodo para no destruir sin estar logeado


 # metodo para mostrar MIS PINS. (LOS PINS DE UN USUARIO LOGUEADO.)

 def contactme
  @blog = Blog.find_by_slug(params[:id])
   render layout: "bloglayout/blogcontact"



 end

  def myblogs
    @blogs = current_user.blogs   
  end



  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all.sorted
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show     
   
    #aqui cargamos un objeto post

    #PREGUNTAR POR EL BLOG: ETC...que significa.
    @post = Post.new blog: @blog
    @posts = @blog.posts.sorted

    if @blog.designLayout == 1

      #layout(template_name, conditions = {}, auto = false) public
      #http://apidock.com/rails/ActionController/Layout/ClassMethods/layout
      render layout: "bloglayout/blogindex"
      
     else
      render layout: "bloglayout/blogindex2"
     
     end

  end

  # GET /blogs/new
  def new
    @blog = Blog.new
    @b = Blog.all

     
  @categories = Category.all


  end

  # GET /blogs/1/edit
  def edit
    @blog = Blog.find_by_slug(params[:id])
    @categories = Category.all

  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    #aqui agregamos el id del usuario logueado y lo asociamos al nuevo blog creado
    @blog.user_id   =   current_user.id

    respond_to do |format|
      if @blog.save
        format.html { redirect_to root_path, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        # format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to myblogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
       #@blog = Blog.find(params[:id])
        @blog = Blog.find_by_slug(params[:id])

        
       
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:siteTitle, :siteDescription, :siteHeader, :user_id, :category_id, :designLayout)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
 

<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
       <h2><%= pluralize(@blog.errors.count, "error") %> campos son requeridos:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 



<div class="form-group">
  <div class="field">
    <%= f.label :siteTitle, "¿Que nombre le pondrás a tu SuperBlog?" %><br>
    <%= f.text_field :siteTitle, class:'form-control' %>
  </div>
  </div>

<div class="form-group">
  <div class="field">
    <%= f.label :siteDescription, "una Frase cool para tu SuperBlog:" %><br>
    <%= f.text_field :siteDescription, class:'form-control' %>
  </div>
  </div>

  <div class="form-group">
  <div class="field">
    <%= f.label :siteHeader, "Tu Background favorito aquí:" %><br>
    <%= f.text_field :siteHeader, class:'form-control' %>
  </div>
  </div>
 
 <div class="form-group">
  <div class="field">
    <%= f.label :category_id, "Categoria a la que pertenece:" %><br>
    <%= collection_select(:blog, :category_id, @categories, :id, :category_name, prompt: true, class: 'form-control') %>
   </div>
  </div>

<div class="form-group">
  <div class="field">
    <%= f.label :designLayout, "Tu layout:" %><br>

 
    <%= f.select(:designLayout, [['Classic', 1], ['fancy', 2]],  { :class => 'form-control' }) %>

 
 
     
  </div>
  </div>



   <br>
   <div class="form-group">
  <div class="actions">
    <%= f.submit class:"btn btn-success" %>
  </div>
  </div>

<% end %>

app/views/blogs/contactme.html.erb
 
  

<div class="container text-center">
	

	<div class="row">
		 
		
				<ul class="list-unstyled">
					<li><img src="http://placehold.it/150x150" class="img-circle img-thumbnail"></li>
					<li> <h3> Hola! Soy <strong><%=  @blog.user.username  %></strong> </h3> </li>
					<li>  <p> asdasd <%=  @blog.user.bio  %> <br></p></li>
					<li> me contecté por última vez el: <%=  @blog.user.last_sign_in_at  %></li>					 
				</ul>
					  

				<ul class="list-inline">
					<li> <a href="http://www.twitter.com/<%= @blog.user.twitter %>" target="_blank"><%=  image_tag("twitter.png") %></a> </li>					
					<li> <a href="http://www.facebook.com/<%= @blog.user.twitter %>" target="_blank"><%=  image_tag("facebook.png") %></a></li>
					<li> <a href="http://www.linkedin.com/<%= @blog.user.twitter %>" target="_blank"><%=  image_tag("linkedin.png") %></a></li>
					<li> <a href="mailto:<%= @blog.user.twitter %>" target="_blank"><%=  image_tag("email.png") %></a></li>



				</ul> 


			</div>

	</div>

</div>



 
 <!-- 
  t.string   "email",                  default: "", null: false
    t.string   "encrypted_password",     default: "", null: false
    t.string   "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.integer  "sign_in_count",          default: 0,  null: false
    t.datetime "current_sign_in_at"
    t.datetime "last_sign_in_at"
    t.inet     "current_sign_in_ip"
    t.inet     "last_sign_in_ip"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "username"
    t.text     "bio"
    t.string   "twitter"
    t.string   "facebook"
    t.string   "linkedin" -->

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
 

 
</style>

<h1 class="text-center">Hola, <% if user_signed_in? %> 
<strong><%= current_user.username %>! </strong>



<% end  %>
Estos son los últimos SuperBloggers en <strong>blog<span class="text-primary glyphicon glyphicon-magnet small " aria-hidden="true"></span>eate</strong>
  </h1>

<div class="clearfix"></div>
<hr class="small">
 <div class="row">
   
   <div class="col-md-6 text-right">   
      <%= image_tag("heroes2.gif", class:'text-center ') %>
    </div>

     <div class="col-md-6 ">
     <p style="margin-top:30px;"> 

<% if user_signed_in? %>

<%= link_to 'Crear Mi SuperBlog!', new_blog_path, class: 'btn btn-lg btn-success' %>

<% else  %>

<%= link_to "Se un SuperBlogger!", new_user_registration_path, class: 'btn btn-lg btn-danger text-center' %> 

<% end %>

</p>

   </div>


 </div>

 
  <div class="row">
<!-- http://placehold.it/350x150 -->

         <% @blogs.each do |blog| %>
              <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                  <img src="<%= blog.siteHeader %>" alt="<%= blog.siteTitle %>" style="height:200px;" class="img-rounded "   >
                  <div class="caption">
                    <h3><%= blog.siteTitle %></h3>
                      <p><%= blog.user.username %></p>


                      <p><span class="label  label-<%= blog.category.category_name %>"><%= blog.category.category_name %></span> </p>
                    <p>
                    
                      <%= link_to 'Leer!', blog, class:"btn btn-primary" %>
                    <a href="#" class="btn btn-primary" role="button">compartir!</a>  </p>
                  </div>
                </div>
              </div>
             
        <% end %>

    </div> 

app/views/blogs/myblogs.html.erb
 
<% if user_signed_in? && !@blogs.blank? %>

    <%= link_to 'Nuevo Blog', new_blog_path, class:'btn btn-success' %>

<% end %>

<% if user_signed_in? %>
  <h1 class="text-center"><strong><%= current_user.username %></strong>, estos son tus Blogs. </h1>
  <h3 class="text-center">¿Sobre qué escribirás hoy?</h3>
<% end  %>
<br>

<p id="notice"><%= notice %></p>

   

   <!-- iteramos los pins del usuario ACTUAL.
   se comunica con el metodo mypins del controller pins_controller.rb -->

  <% if @blogs.blank?  %>

  <div class="  col-md-12 text-center">
           
          <%= image_tag("frank.png", class:' text-center franky') %>
          <br>
<h3>  ups no tienes blogs creados!</h3> 
      <%= link_to 'Crear Mi SuperBlog!', new_blog_path, class: 'btn btn-lg btn-success' %>
</div>

<% else  %>
    <% @blogs.each do |blog| %>



      <div class="col-md-4">

          <div class="thumbnail">

                   
                <img src="<%= blog.siteHeader %>" alt="<%= blog.siteTitle %>" style="height:200px;"   >


              <div class="caption">
              <h3><%= blog.siteTitle %></h3>
                <p><%= blog.user.username %></p>
                 <p> <%= time_ago_in_words blog.created_at %></p>
               
                  <%= link_to 'visitar mi blog', blog, class: 'btn btn-default btn-xs' %> 

                 <%= link_to 'Editar', edit_blog_path(blog), class: 'btn btn-info btn-xs' %>

                 <%= link_to 'Borrar', blog, method: :delete, data: { confirm: 'estas seguro?' }, class: 'btn btn-danger btn-xs' %> 
              </div>



            
           
           </div><!-- //cierra thumbnail-->

        </div>  <!-- //cierra col-md-3-->
 

    <% end %>


    <% end   %>
 
<br>



 

app/views/blogs/new.html.erb
<h1>Hola <%= current_user.username %></h1>

<h3>Genial! decidíste crear un SuperBlog!</h3>

<br>

<%= render 'form' %>

<br>
<%= link_to 'Back', blogs_path, class:"btn btn-default" %>

app/views/blogs/show.html.erb
 
 <!-- AQUI MUESTRO LOS POSTS DEL USUARIO ACTUAL -->
<!-- RECURSO ANIDADO ENTRE BLOG Y POSTS -->

<!--   blog > show  -->
    
	 
	


<!-- aqui se carga views/layouts/bloglayout/ blogindex2.html.erb

-->
 
 