config/routes.rb
Rails.application.routes.draw do
  resources :categories

  get 'pages/equipo'

  get 'pages/contacto'

  get 'pages/services'

  devise_for :users
  get 'comments/create'

  get 'comments/update'

  get 'comments/destroy'

  get 'myblogs' => 'blogs#myblogs'
 
  get 'blogs/:id/contactme' => 'blogs#contactme', as: :contactme
 
   

    
        
 
 
  resources :blogs, :path => ''

    resources :blogs do
       resources :posts do
          resources :comments
      end  
  end

 

  root 'blogs#index'

end

app/views/layouts/bloglayout/_allposts.html.erb
<% if @posts.blank?  %>
<br>
<h2><%= @post.blog.user.username %> no se siente inspirada aún para escribir artículos...OK?</h2>

<%= image_tag("hum3.gif", class:'img-responsive') %>


<% else  %>

<% @posts.each do |post| %>
<div class="block-post">
	<h3><strong><%= post.entryTitle %></strong></h3>

	<blockquote class="">

		<p><%= truncate(post.entryContent, length: 140) %></p>
		<footer>escrito por <cite title="Source Title"><%= post.blog.user.username %>,  
			<%= time_ago_in_words(post.created_at)  %>
		</cite></footer>
	</blockquote>
	
	<!-- quier el username del usuario del blog del post. -->
	
	<%= link_to 'Leer más...', [@blog, post], class: 'text-info lead' %>
	
	
	
	<!--  <p>  post.blog.id </p> -->
	
</div>


<% end %>


<% end %>

app/views/layouts/bloglayout/_formwriter.html.erb
<% if user_signed_in? && current_user.id == @blog.user.id %>

<div class="col-md-12" style="opacity:0.9;">
	
	
	<%= form_for([@blog, @post]) do |f| %>
	

	<div class="form-group">
		<div class="field">
			<%= f.text_field :entryTitle, class: 'form-control' %>
		</div>
	</div>

	<div class="form-group">
		<div class="field">
			
			
			<%= f.text_area :entryContent, :cols => "10", :rows => "10", class: 'form-control' %>

			
		</div>
	</div>
	
	<div class="actions">
		<%= f.submit class: "btn btn-success" %>
	</div>
	<% end %> 

</div><!-- .col-md-5 -->

<% end %>

app/views/layouts/bloglayout/_jumbotron.html.erb
 <!-- Main jumbotron for a primary marketing message or call to action -->
 <div class="jumbotron" style="background:url(<%= @blog.siteHeader %>) repeat;">
  <div class="container">

    <div class="row">
      
      <div class="col-md-2">
        <p> &nbsp;</p>
        
         <%= image_tag("danigatt.jpeg", class:'img-circle img-thumbnail text-center img-responsive', width: '150px', height:'150px') %> 

         <br><br>
 <p class="text-center">  <%= tweet_button(:via => "danigattoni_", :text => "Check this out! #blogueate", :count =>'horizontal') %></p>

 


      </div>


      <div class="col-md-8">
       <p> &nbsp;</p>
       <h1><%=  @blog.siteTitle %>  </h1>
       <p class="siteDescription">  <%=  @blog.siteDescription %></p>        
       
       <p> &nbsp;</p>
     </div>

   </div>
   

       <!--  <a class="btn btn-primary btn-lg" href="<%=  contactme_path %>" >  @blog.user.username  &raquo;</a></p>
     -->


   </div>
 </div>

app/views/layouts/bloglayout/_navbar.html.erb
  

<nav class="navbar navbar-fixed-top navbar-inverse" >
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <% if user_signed_in? %>
      <a class="navbar-brand" href="<%= myblogs_path %>">Volver a mis Blogs</a>
      <% else %>
      <a class="navbar-brand" href="<%= root_path %>">Ver mas Blogs</a>
      <% end  %>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="<%= blog_path %>">Home</a></li>
        

        <li><a href="<%=  contactme_path %>">Contact <%= @blog.user.username  %></a></li>
      </ul>
    </div><!-- /.nav-collapse -->
  </div><!-- /.container -->
</nav><!-- /.navbar -->

app/views/layouts/bloglayout/_social.html.erb
<ul class="list-inline text-center">
	<li> <a href="http://www.twitter.com/<%= @blog.user.twitter %>" target="_blank"><%=  image_tag("twitter.png") %></a> </li>					
	<li> <a href="http://www.facebook.com/<%= @blog.user.twitter %>" target="_blank"><%=  image_tag("facebook.png") %></a></li>
	<li> <a href="http://www.linkedin.com/<%= @blog.user.twitter %>" target="_blank"><%=  image_tag("linkedin.png") %></a></li>
	<li> <a href="mailto:<%= @blog.user.twitter %>" target="_blank"><%=  image_tag("email.png") %></a></li>



</ul> 

app/views/layouts/bloglayout/_userinfo.html.erb
<div class="col-md-12 text-center">
	<br>

	<ul class="list-unstyled" style="color:white; text-shadow:0 1px 5px rgba(0, 0, 0, 0.3)">
		<li>
			 <%= image_tag("danigatt.jpeg", class:'img-circle img-thumbnail text-center img-responsive', width: '150px', height:'150px') %>


		 </li>
		<li>  <h3 class="text-uppercase"> <strong><%=  @blog.siteTitle  %> </strong><br></h3></li>
			<li>   <strong> <%=  @blog.user.bio  %> </strong>  </li>
					<li>  última conexión <%=  @blog.user.last_sign_in_at  %></li>	

		<li><%= tweet_button(:via => "danigattoni_", :text => "#blogueate") %>

		</li>
	</ul>

</div>

app/views/layouts/bloglayout/blogcontact.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Blogueate</title> 

	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
	
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	
	<link href='http://fonts.googleapis.com/css?family=PT+Serif' rel='stylesheet' type='text/css'>
	
	<%= csrf_meta_tags %>
	
</head>
<body>
	
	<%= render 'layouts/bloglayout/navbar' %>
	
	
	<div class="row" style="margin-top:50px; min-height:691px; background:url(<%= @blog.siteHeader %>) repeat;">
		

		<div class="col-md-12">
			
			<%= render 'layouts/bloglayout/userinfo' %>

			<%= render 'layouts/bloglayout/social' %>



		</div>


	</div><!-- row-->

	


	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>

</body>
</html>

app/views/layouts/bloglayout/blogindex.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Blogueate laout blogindex</title> 

	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
	
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	
	<link href='http://fonts.googleapis.com/css?family=PT+Serif' rel='stylesheet' type='text/css'>
	
	<%= csrf_meta_tags %>
	
</head>
<body>
	
	<%= render 'layouts/bloglayout/navbar' %>
	<%= render 'layouts/bloglayout/jumbotron' %>


	
	<div class="row" style="margin-top:50px;">
		
		<div class="col-md-5">
			<%= render 'layouts/bloglayout/formwriter' %>
		</div>
		

		<div class="col-md-7">
			
			<%= render 'layouts/bloglayout/allposts' %>

		</div>


	</div><!-- row-->

	


	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>


	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>

</body>
</html>

app/views/layouts/bloglayout/blogindex2.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Blogueate laout blogindex</title> 

	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
	
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	
	<link href='http://fonts.googleapis.com/css?family=PT+Serif' rel='stylesheet' type='text/css'>
	
	<%= csrf_meta_tags %>

	<style>
		
		
		
	</style>
	
</head>
<body>
	<!-- formato de layout tipo blog 2 -->
	<%= render 'layouts/bloglayout/navbar' %>

	
	<div class="row" style="margin-top:50px;">

		<div class="col-md-5 site-header" style="background:url(<%= @blog.siteHeader %>) repeat;  background-size: cover;">
			
			
			<%= render 'layouts/bloglayout/userinfo' %>

			<%= render 'layouts/bloglayout/formwriter' %>

		</div>

		<div class="col-md-6 content-area"> 

			<%= render 'layouts/bloglayout/allposts' %>	

		</div>
	</div>
	
	

	
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>


	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>

</body>
</html>