config/routes.rb
Rails.application.routes.draw do
  resources :categories

  get 'pages/equipo'

  get 'pages/contacto'

  get 'pages/services'

  devise_for :users
  get 'comments/create'

  get 'comments/update'

  get 'comments/destroy'

  get 'myblogs' => 'blogs#myblogs'
 
  get 'blogs/:id/contactme' => 'blogs#contactme', as: :contactme
 
   

    
        
 
 
  resources :blogs, :path => ''

    resources :blogs do
       resources :posts do
          resources :comments
      end  
  end

 

  root 'blogs#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :blog
	has_many :comments

	validates :entryTitle, presence: { message: "ups requerido!"}
    validates :entryContent, presence: { message: "ups requerido!"}


	scope :sorted, -> {order('id desc')}

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  #before_action :authenticate_user!, only: [:destroy, :create, :update, :show] #metodo para no destruir sin estar logeado


  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show

   @blog =Blog.find_by_slug(params[:blog_id])


    #instancio un nuevo comment
    @comment = Comment.new post: @post
    

    #recopilo todos los comments del post actual.
    @comments = @post.comments.all

    @count_comments = @post.comments.count
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  #@blog.user.username  
  # <%= @blog.id %>
  def create


  #asignamos al objeto pin un registro que corresponde a pin_id que estamos evaluando, en la url
  @blog =Blog.find_by_slug(params[:blog_id])
  #
  @post = Post.new(post_params)

  #al comentario le asocio un pin especifico, el cargado en memoria, a esto le asigno el objeto @pin
  @post.blog = @blog

  #guardo el objeto pin llamando a su metodo .save
  @post.save

  #finbalmente se redirige al al pin con el comentario /pìn/1
  redirect_to @blog
    
     
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:entryTitle, :entryContent, :blog_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :entryTitle %><br>
    <%= f.text_field :entryTitle %>
  </div>
  <div class="field">
    <%= f.label :entryContent %><br>
    <%= f.text_field :entryContent %>
  </div>
  <div class="field">
    <%= f.label :blog_id %><br>
    <%= f.number_field :blog_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Entrytitle</th>
      <th>Entrycontent</th>
      <th>Blog</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.entryTitle %></td>
        <td><%= post.entryContent %></td>
        <td><%= post.blog_id %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<!--   CONTROLLER POST >  POST > VIEW SHOW  -->

<div class="row">

<div class="col-md-12">
	
	<ol class="breadcrumb">
	<li>Estás en: </li>
	  <li><a href="<%= myblogs_path %>">Mis Blogs</a></li>
	  <li><a href="<%= blog_post_path %>"><%= @blog.siteTitle %></a></li>
	  <li class="active"><%= @post.entryTitle %></li>
	</ol>

</div>

 

<div class="col-md-12">
 <p class="text-right">  <%= tweet_button(:via => "danigattoni_", :text => "Check this out! #blogueate", :count =>'vertical') %></p>

</div>
 

<div class="col-md-6 col-md-offset-3">

<p class="text-center">
	 <%= image_tag("danigatt.jpeg", class:'img-circle img-thumbnail text-center img-responsive', width: '100px', height:'100px') %> 

</p>

	<h1 class="text-center">
		<strong><%= @post.entryTitle %></strong>
	</h1>

	<blockquote class="blockquote-reverse">

		<p><%= truncate(@post.entryContent, length: 140) %></p>

		<footer>escrito por <cite title="Source Title"><%= @post.blog.user.username %>, <%= time_ago_in_words(@post.created_at) %></cite></footer>

	</blockquote>


 
	<div class="postContent">
		<%= @post.entryContent %>

	 <br>
	 <br>
	 

		 

   </div>

	 
</div>
<!-- estas en post > show.html.erb -->

<div class="clearfix"></div>


<div class="col-md-6 col-md-offset-3">
<%= form_for([@blog, @post, @comment]) do |f| %>	  

<div class="form-group">
<div class="field">
	 <%= f.label :comment, "Deja un comentario:" %><br>
	 <%= f.text_area :comment, :cols => "10", :rows => "3", class: 'form-control' %>
</div>
</div>	   
<div class="actions">
 

<%= f.submit :value => "enviar", class: "btn btn-success pull-right"  %><br><br>
</div>
<% end %> 

</div><!-- col md 6--> 


<div class="clearfix"></div>


<div class="col-md-6 col-md-offset-3">
 <h4 class="text-center">Este Artículo 
<% if @count_comments == 0 %>
no tiene
<% else  %>
 tiene <%= @count_comments %> 
 <% end  %>comentarios.
 </h4>


<!-- 
id: 15,
comment: "erwer",
post_id: 51,
user_id: 5,
created_at: Mon, 16 Feb 2015 01:32:53 UTC +00:00,
-->

	<% @comments.each do |c| %>
 			<div class="col-md-12" style="border-bottom:1px dashed #cdcdcd; padding-top:20px;">
 			<blockquote>
 			<span class="small"><strong> <%=  c.user.username %></strong>
 			<br><span class="text-info "><%=  time_ago_in_words(c.created_at) %></span>				
 			</span> 
			<span class="small"> <%= truncate(c.comment, length: 140) %></span>
			</blockquote>			 
			</div>
	<% end %>

</div>
 



</div>